DROP TABLE "FAHRSCHEIN" cascade constraints;

CREATE TABLE "FAHRSCHEIN" 
   (	"FID" NUMBER NOT NULL ENABLE, 
	"FK_KUNDE" NUMBER NOT NULL ENABLE, 
	"FK_STRECKE" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "FAHRSCHEIN_PK" PRIMARY KEY ("FID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
   ENABLE, 
	 CONSTRAINT "KUNDE_FK" FOREIGN KEY ("FK_KUNDE")
	  REFERENCES "KUNDE" ("KID") ENABLE, 
	 CONSTRAINT "STRECKE_FK" FOREIGN KEY ("FK_STRECKE")
	  REFERENCES "STRECKE" ("SID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
   ;
