DROP TABLE "KUNDE" cascade constraints;

  CREATE TABLE "KUNDE" 
   (	"KID" NUMBER NOT NULL ENABLE, 
	"VORNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NACHNAME" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "KUNDE_PK" PRIMARY KEY ("KID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
    ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
   ;
