DROP TABLE "RESERVIERUNG" cascade constraints;

CREATE TABLE "RESERVIERUNG" 
   (	"RID" NUMBER NOT NULL ENABLE, 
	"ZUG_FK" NUMBER NOT NULL ENABLE, 
	"PLATZ" NUMBER NOT NULL ENABLE, 
	 CONSTRAINT "RESERVIERUNG_PK" PRIMARY KEY ("RID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
   ENABLE, 
	 CONSTRAINT "FK_ZUG" FOREIGN KEY ("ZUG_FK")
	  REFERENCES "ZUG" ("ZID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
   ;
 
