DROP TABLE "STRECKE" cascade constraints;

  CREATE TABLE "STRECKE" 
   (	"SID" NUMBER NOT NULL ENABLE, 
	"VON" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NACH" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	 CONSTRAINT "STRECKE_PK" PRIMARY KEY ("SID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOCOMPRESS LOGGING
    ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
   ;
 
